# Generated by Django 5.0.1 on 2024-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edible', models.BooleanField(default=False)),
                ('purpose', models.CharField(blank=True, choices=[('FOR_KITCHEN', 'Для кухни'), ('FOR_BATHROOM', 'Для бани'), ('VISITING', 'В гости'), ('COSMETIC_KITS', 'Косметические наборы'), (None, 'Без назначения')], max_length=47, null=True, verbose_name='Назначение')),
                ('package', models.CharField(blank=True, choices=[('BASKET', 'Корзина'), ('BOX', 'Коробка'), ('PACKAGE', 'Пакет'), ('CASE', 'Ящик'), (None, 'Без упаковки')], max_length=47, null=True, verbose_name='Упаковка')),
                ('vendor_code', models.IntegerField(unique=True, verbose_name='Артикул')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
            ],
        ),
    ]
