# Generated by Django 5.0 on 2023-12-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="slug",
        ),
    ]
