# Generated by Django 5.0.1 on 2024-04-20 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(default='Полярная 34 к 1', max_length=50, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='delivey_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='orders',
            name='final_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая стоимость'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('В обработке', 'In Processing'), ('Не оплачен', 'Not Paid'), ('Принят', 'Accepted'), ('Оплачен', 'Paid'), ('В службе доставки', 'In Delivery Service'), ('Доставлен', 'Delivered'), ('Получен', 'Received')], default='В обработке', max_length=25, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='products_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена всех товаров без скидки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='receive_method',
            field=models.CharField(choices=[('1', 'Доставка курьером по Москве'), ('2', 'Доставка СДЕКом'), ('3', 'Самовывоз')], default='3', max_length=50, verbose_name='Способ получение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products', verbose_name='Продукт'),
        ),
    ]
