# Generated by Django 5.0 on 2023-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                default="Москва Рождественская улица д4", max_length=500
            ),
            preserve_default=False,
        ),
    ]
