# Generated by Django 5.0 on 2023-12-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consentPersonalData",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="consentReceiveNews",
            field=models.BooleanField(default=False),
        ),
    ]
